project:
  type: website
  output-dir: docs

website:
  title: "EcoPulse"
  open-graph:
      locale: es_ES
      site-name: Quarto
  page-footer:
    center:
      "Patrick Schaefer - ecopulseanalytics[at]gmail.com"
    background: info
  navbar:
    #logo: "figures/logo.png"
    #logo-href: home.qmd
    pinned: true
    collapse: true
    background: info
    search: false
    left:
      - text: Home
        href: index.qmd
      - text: "Services"
        menu:
         - text: Data Analysis and Visualization
           href: services/services_DaVis.qmd
         - text: Dashboard, Database and Tool Development
           href: services/services_dev.qmd
         - text: Training
           href: services/services_trn.qmd
      - text: Examples
        href: examples.qmd
      - text: About
        href: contact.qmd
  # cookie-consent:
  #   type: express
  #   style: headline
  #   palette: dark

format:
  html:
    theme: minty
    css: styles.css
    email-obfuscation: javascript
    link-external-newwindow: true
    #toc: true

editor: source

